### ISSUE TITLE
Could i get map with a synchrotron?

### ISSUE THREAD

**Issue by danielboos1** [Lach01298/QMD#49]
Hi, 
This really isn't an issue or anything but I was wondering if I could get minecraft map that has a synchrotron i want to experiment around with it. I'm still in highschool and this just to advanced for me build one. But I got a moderate understanding how they work, I want to experiment around with things. Would be much appreciated, Thanks!

**Comment by Lach01298** [comment]
[QMD.zip](https://github.com/Lach01298/QMD/files/6137770/QMD.zip)
Here is the QMD Showcase world it has a bunch of setups to show a lot of the features of QMD. It may seem complex because there is a bunch of setups some merged together but its really not just flip the levers (and push the buttons to change things)

QMD isn't really that complex in many respects, the synchrotrons are basically determined by 2 equations that you can just plug the numbers in. They are actually less complex to build/design than NC fission reactors. The concepts may seem complex but they are fairly simple and no knowledge of particle physics is really required (maybe just what is a proton, neutron and electron are)
