### ISSUE TITLE
Crafttweaker Support

### ISSUE THREAD

**Issue by lunareclipse-64** [Lach01298/QMD#58]
Does the **Neutral Exotic Containment** have crt support?
I can't find it in QMDCrafttweaker.
It'd be nice if you can add this function.

**Comment by Lach01298** [comment]
It doesn't because the way it works. I could add recipes for the fluid product but there is no way to get the fluid out because it doesn't have a custom cell.

To make it work with any fluid I would have to make quite a few code changes that currently I'm not willing to do.

**Comment by lunareclipse-64** [comment]
OK，I see.The cell is unlike the bucket.I'll turn to the Beam Dump as an alternative.

**Comment by Lach01298** [comment]
Yeah the cell isn't a bucket because I didn't want antimatter to be able to be stored in a bucket. So ironically I now have the issue of it being incompatible because I made it purposely incompatible. I'll keep this open as an enhancement because I'm not ruling out that I wont eventually do it but it's currently not a high priority.

**Comment by Lach01298** [comment]
Added in 1.2
